### ISSUE TITLE
During executing command 'bin/magento fastly:maintenance' error appeared

### ISSUE THREAD

**Issue by bbakalov** [fastly/fastly-magento2#642]
_Magento version 2.4.6_

During executing command
`php bin/magento fastly:maintenance`

Error appeared:

> There is an error in /app/jmalmxr5itqso_stg/vendor/symfony/console/Command/Command.php at line: 301
>   Return value of "Fastly\Cdn\Console\Command\SuperUserCommand\Interceptor::execute()" must be of the type int, "null" returned.#0 /app/jmalmxr5itqso_stg/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>   #1 /app/jmalmxr5itqso_stg/vendor/magento/framework/Interception/Interceptor.php(138): Fastly\Cdn\Console\Command\SuperUserCommand\Interceptor->___callParent('run', Array)
>   #2 /app/jmalmxr5itqso_stg/vendor/magento/framework/Interception/Interceptor.php(153): Fastly\Cdn\Console\Command\SuperUserCommand\Interceptor->Magento\Framework\Interception\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by bbakalov** [comment]
Pull request with changes added https://github.com/fastly/fastly-magento2/pull/643
